---
abstract: 'POE enabled CPAN smoke testing with added value.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  File::Spec: 0
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Digest::MD5: 0
  Module::Pluggable: 0
  Object::Accessor: 0
  POE: 1.0001
  Params::Check: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_04
