---
abstract: 'POE enabled CPAN smoke testing with added value.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::Harness: 3.14
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Digest::MD5: 0
  Env::Sanctify: 0.04
  Module::Pluggable: 0
  Object::Accessor: 0
  POE: 1.0001
  Params::Check: 0
  String::Perl::Warnings: 0.04
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-smokebox/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-smokebox.git
version: 0.40
